### ISSUE TITLE
Auto submit once file has been dropped?

### ISSUE THREAD

**Issue by deronsizemore** [devbridge/html5-file-uploader#7]
Hey! I'd like to use this but before diving in, was wondering if there's a way for me to trigger a form submission or something so that once the file has been dropped into the upload area, I can submit the form and advance users to the second step of my upload process?

**Comment by tkirda** [comment]
When passing file there is `onCompleted` callback, where it's up to you what to do next.

**Comment by deronsizemore** [comment]
Thanks
