### ISSUE TITLE
requirejs required?

### ISSUE THREAD

**Issue by jpdevries** [devbridge/html5-file-uploader#8]
I've been able to get html5-filte-uploader working but am confused by something in the docs. It says it is vanillajs and requires no libraries, but seems to require require.js. Is it possible to use html5Upload.js completely standalone?

**Comment by tkirda** [comment]
You are right, it's an AMD module, I need to update it not to require it. You can remove `define` and just invoke function immediately if you want to use it as a global:

Replace: 

    define(function (){
      // contents
    });

With:

    var html5Upload = (function(){
      // contents
    }());

**Comment by jpdevries** [comment]
thanks for confirming that @tkirda. I was a bit confused.

great work btw really enjoying this component :+1:
